Fix python 3.13 deprecation of typing.re
In python 3.13, `typing.re` was removed (deprecated since Python 3.8). See https://github.com/python/cpython/issues/92871

This pr refactors to support python 3.13 which currently throws

```python
ImportError: cannot import name 're' from 'typing' 
```